version: '3.8'

services:
  homeassistant:
    image: "ghcr.io/home-assistant/home-assistant:stable"
    container_name: ha-dev
    ports:
      - "8123:8123"
    volumes:
      - ./.config:/config
      - ./config/configuration.yaml:/config/configuration.yaml
      - ./custom_components:/config/custom_components
    restart: unless-stopped
